### ISSUE TITLE
0.1% of our addresses is wrongly generated

### ISSUE THREAD

**Issue by phuongnd08** [GemHQ/money-tree#16]
We use money-tree to maintain our wallet and generated around 30k+ addresses, each associated with a unique path
Recent audit revealed that there are 26 paths would generate a different address now compared to 6 months ago!

What could be the possible causes of this? Is there any way to recover the fund sent to old generated address? And how to prevent this from happening again?

**Comment by jvergeldedios** [comment]
Did you upgrade money-tree at any time during that span? I'm not sure I understand what "different addresses compared to 6 months ago" means. Can you post some examples?

**Comment by phuongnd08** [comment]
Yes, we did. I notice that changing back to the old version and use from_serialized_address instead of from_bip32 (the new version) reproduce the old address. Everything is still recoverable.
