### ISSUE TITLE
Ethereum Support

### ISSUE THREAD

**Issue by mhluska** [GemHQ/money-tree#25]
Can this be used for generating Ethereum addresses from a seed? Looks like some gems like [this one](https://github.com/DigixGlobal/ruby-eth/blob/master/lib/eth/key.rb) are attempting it but I can't get their generated addresses to work properly. The addresses the gem I linked generates don't match the ones that MyEtherWallet or this [tool](https://freewallet.org/bip39-recovery-from-mnemonic-bitcoin-and-other-cryptocurrencies) would generate. I'm not experienced enough to know why though.

**Comment by nofxx** [comment]
It works just fine. You must use Key#private_hex. (Myetherwallet and eth gem).
Now curious about mnemonic words ones... will investigate.

**Comment by mhluska** [comment]
Can you elaborate? I'm trying to use an extended public key to create Ethereum addresses. Here's how I'm trying it:

```
require 'money-tree'
require 'eth'
key = 'xpub6Dv28vySKcyJSvYivLP8PEedEZf6Cut2D7cUUaPgushD7MNWvpsy34oZaxrAbdbtuGN61hMLbv17tc4hFPfiYN4oMLJxt9SyvfoxtJadbiR'
master = MoneyTree::Node.from_bip32(key)
node = master.node_for_path("m/44'/60'/0'/0") # This step throws MoneyTree::Node::PrivatePublicMismatch
Eth::Utils.public_key_to_address(node.public_key.to_hex)
```

**Comment by nofxx** [comment]
Sorry @mhluska , apprentice on the wheel here, but maybe related to #22 ?

**Comment by mhluska** [comment]
Seems to be related. Looks like not much is happening to help fix the issue? I can give it a shot this week.

**Comment by mhluska** [comment]
So the `MoneyTree::Node::PrivatePublicMismatch` happens because hardened derivations can't happen without a master private key. If I replace the xpub with an xprv, it runs fine but the resulting Ethereum address is still incorrect.

**Comment by jackkinsella** [comment]
I ran into the same problem today. Everything works just dandy with the following code

```ruby
   # Assumes that the 'eth' gem is available
   Eth::Utils.public_key_to_address(node.public_key.uncompressed.to_hex)
```

**Comment by thedoctor** [comment]
@mhluska Correct regarding the hardened derivation issue.
@jackkinsella is (ostensibly) correct with the use of `uncompressed`. I don't know the `Eth::Utils` class myself, but it clearly expressed uncompressed public keys.

It's probably not a likely that we'll add support for ethereum addresses directly to this repo as that's beyond the scope of money-tree

**Comment by krtschmr** [comment]
@thedoctor  "money-tree" the name itself should support everything. not just bitcoin 👍
