### ISSUE TITLE
Update gemspec / publish gem

### ISSUE THREAD

**Issue by mhluska** [GemHQ/money-tree#27]
It looks like the `.gemspec` file was last updated 3 years ago and the [published gem](https://rubygems.org/gems/money-tree/versions/0.9.0) is quite old.

I'm trying to use this project in [cryptocoin_payable](https://github.com/Sailias/cryptocoin_payable/issues/5) which [doesn't seem to be possible](https://stackoverflow.com/a/6499472/659910) unless we publish this fork as a gem.

Can we update the gemspec file and publish a gem?

**Comment by JokerCatz** [comment]
yep，& I get "warning: constant ::Bignum is deprecated" when I use "gem i money-tree" ( version 0.9.0 ) but it look like fixed in this repository , I think you need upgrade the version first?

**Comment by mhluska** [comment]
@thedoctor are you still a maintainer for this project?

**Comment by lgn21st** [comment]
Could we bump to the new version, pls!

**Comment by thedoctor** [comment]
I tagged a v0.10.0 release; there was some confusion with previous tags.
I'm waiting on access to the private key for publishing to rubygems; when I get that, I'll publish the release.

**Comment by lgn21st** [comment]
@thedoctor looking forward to it, thx.

**Comment by thedoctor** [comment]
Published! 

NOTE: Had to replace the cert, so anyone using this gem in HighSecurity mode will need to add the new trusted certificate.

Sorry everybody for the delay; while we're not actively using this repository and can't commit to aggressive feature development, we'll do our best to keep it functional. Best way to get our attention for future issues is to tag me in your issue directly (he said reluctantly).

If anyone is interested in helping to maintain this repo, Gem may be receptive to that.
Cheers!
