### ISSUE TITLE
can't import to electrum or the other way

### ISSUE THREAD

**Issue by krtschmr** [GemHQ/money-tree#36]
I always struggle here and tried both ways plenty of time

i use the rubygem "moneytree" and electrum 3.3

    @master = MoneyTree::Master.new
    @master.to_bip32(:private)

this will give me `tprv8ZgxMBicQKsPe8hnfLVQdtZk2qMKnnDQs2ZKLgoJQBhedKQ5vB7srAb6Tk2iUYNkhaacTjNP9WzkbjCqPjk8ExUFGECbiR1Z8tZDs76jytn` 

however, i can't import this in electrum. the `next` button is just non active.

---------

i tried the other way around and created a wallet with seed `fabric body bright coffee special music virus raccoon side double shield shrug` and exported the master public key which will gives me `xpub661MyMwAqRbcGq54zC5FfD3rTjgcAGd36JvtW6r4RGheQjSdUVqAS9Q1DLAvzyvvxdYziZced4Y6kHLCqo73vuB4gGSpt6tJwtCWYm8zsBb` 

now i'll run the following

    master_pub_key = "xpub661MyMwAqRbcGq54zC5FfD3rTjgcAGd36JvtW6r4RGheQjSdUVqAS9Q1DLAvzyvvxdYziZced4Y6kHLCqo73vuB4gGSpt6tJwtCWYm8zsBb"
    $bitcoin_root_node = MoneyTree::Node.from_bip32(master_pub_key)

    i = 0
    20.times do
      p $bitcoin_root_node.node_for_path("m/0/#{i}").to_address
      i+= 1
    end

all generated addresses will look like this

    mpQPcBLyTqPPCw9dhdXYm3Dvnnn58Y4dwA
    mt6UdprJNAuJUtG3BYWTy3dZrST7nZTwtZ

starting with a small M

however, in electrum all the addresses are starting with `1xxxxx`

what am i doing wrong?

**Comment by artfullyContrived** [comment]
@krtschmr 
`@master.to_bip32(:private)` gives me a private master key that starts with `xprv`

The master key can then be imported into electrum via
`File > New/Restore > Next > Standard Wallet > Use a master key` then paste in the master key. Electrum then correctly generates the addresses.

The converse also works 
```
master_pub_key = "xpub661MyMwAqRbcGq54zC5FfD3rTjgcAGd36JvtW6r4RGheQjSdUVqAS9Q1DLAvzyvvxdYziZced4Y6kHLCqo73vuB4gGSpt6tJwtCWYm8zsBb"
 => "xpub661MyMwAqRbcGq54zC5FfD3rTjgcAGd36JvtW6r4RGheQjSdUVqAS9Q1DLAvzyvvxdYziZced4Y6kHLCqo73vuB4gGSpt6tJwtCWYm8zsBb" 
$bitcoin_root_node = MoneyTree::Node.from_bip32(master_pub_key)
 => #<MoneyTree::Node:0x000055a3cfbc08b8 @depth=0, @parent_fingerprint="00000000", @index=0, @chain_code=103893549000655198865540184515129049159652500395802580949273608524213867841585, @public_key=#<MoneyTree::PublicKey:0x000055a3cfbc0cf0 @options={:compressed=>true}, @raw_key="034523c1ce80328f532f61f486625687daac5cd6489d064d591cc4a4905c5772aa", @group=#<OpenSSL::PKey::EC::Group:0x000055a3cfbc0ca0>, @point=#<OpenSSL::PKey::EC::Point:0x000055a3cfbc0ae8 @group=#<OpenSSL::PKey::EC::Group:0x000055a3cfbc0ca0>>, @key="034523c1ce80328f532f61f486625687daac5cd6489d064d591cc4a4905c5772aa">> 
```

```
20.times do
    p $bitcoin_root_node.node_for_path("m/0/#{i}").to_address
end

"19tSK8Fzeox8Rpg1z4ZAw81bvoBNG2NXXL"
"1DaXLmmKZ9U3hmnRTyY698REzSrQubFWt7"
"1A8VfXh4ysGjvfo49UdZVXidsAP9iU15fc"
"17A4iUyeUcT4X6mFrSSPU1VMoS988oah1x"
"1FU4jxhuvCVkCXdUo7ZzNuSuThVCgm38kx"
"19sUHz9DZ9UeGQ6CrJao7rUWiReaCirJtg"
"1eoQhiqKejd7hQZRLfagy5La31fVdw64Q"
"1EuFfAf4kwTefe2tENS8awkvytu71HfgrQ"
"1hpBSQvHcdJ7ZkbhsACpPFKUae2dCBoBS"
"17phK1ENqHaZspGPNiN6yVX7ZEJZvkpKWN"
"16u4rVzunVuLhEHUDRnpM2BR1RqaN3t6xt"
"1Bc23oGzzoCructsV1kzinChH8DaV2Ua9u"
"1AEtmUZUCxSP71zsSXrqGDv4qLJ528ceA8"
"1MYSq7Q33EH12FJWWxDsx2eu9vSk5tDsFR"
"1A3mrFG6BP74Et9QvgZLPrzfBEobz85ip3"
"12SmawjgrhXZjccu1nXJ5mZ9CB4nCfrPah"
"14Hta1j8y99PrU8Wu5jPNt56MAdZDFbfoq"
"12qQxppSyxtqHi6SYwTQ3L1nMjPXEkMUfy"
"1QgSyxHLfuxwo5b3niEL9dPecmAmehPTf"
```

These are the same address generated in electrum

I have run the above on rails console and used electrum 3.3.4

**Comment by krtschmr** [comment]
@artfullyContrived  i figured out i used my own fork where default everything is on testnet. sometimes i'm stupid :)
