### ISSUE TITLE
`money-tree` performs unsafe FFI and Monkey Patching of OpenSSL

### ISSUE THREAD

**Issue by rickmark** [GemHQ/money-tree#44]
There are two defects:

1. By monkey patching `OpenSSL::PKey::EC::Point` this gem can cause error when other code performs EC operations on a curve other then `secp256k1` - Do not monkey patch the OpenSSL library.
2. By using FFI the gem might load two different `libcyrpto` binaries in the same process.

PR #43 solves both of these issues as well as provides a test to ensure conformance.

**Comment by rickmark** [comment]
Ok - I want to cry on the inside like a winner here....

So this seems to work fine on Ruby 2.7 and greater because they have a more recent compiled OpenSSL extension.  This probably explains why this was needed at all (for before `OpenSSL::PKey::EC::Point.add()` was included).

So, I propose if we are Ruby 2.6 or prior to have it depend on `gem 'openssl'` which gives the required function.

Without this we have the binding problem + if `libcrypto` is out of date we get a late bound FFI problem instead of a compilation issue on gem install.

Updating the PR to reflect

**Comment by rickmark** [comment]
Gem now depends on `gem 'openssl', '>= 2.2'` so that you can be assured of the EC functions

**Comment by zeptonaut** [comment]
Just wanted to ping this: any update on getting #43 merged? I think that at least having some version of the gem that works on both the Rails stable Ruby version and the latest Ruby stable version is a huge improvement over the current state, and it seems like #43 may get us to that point.

**Comment by q9f** [comment]
Yes, very soon. I reviewed #43 yesterday and think it's good to go. I want to conduct further tests on Monday before considering a release.
