### ISSUE TITLE
Hardened key derivation

### ISSUE THREAD

**Issue by assafshomer** [GemHQ/money-tree#7]
Dear Wink.
Does the gem support [hardened key derivation](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki#extended-keys) ?

**Comment by jvergeldedios** [comment]
Yes, see: https://github.com/GemHQ/money-tree#values-of-i-and-i-prime
The prime denotes hardened derivation.

**Comment by assafshomer** [comment]
Thanks Julian.
So do I understand correctly that the split in the code occurs here
<https://github.com/GemHQ/money-tree/blob/master/lib/money-tree/key.rb#L187>
?

Assaf Shomer
+972-58-477-8867
